### ISSUE TITLE
如何导入cs106b的库

### ISSUE THREAD

**Issue by Henry-qing** [Andy-xiaokang/CS106B#1]
大佬您好，请问我如何把文件2021.1里的库导入本地呢

**Comment by Andy-xiaokang** [comment]
看一下 assignment0

**Comment by Henry-qing** [comment]
assgnment0里那个cs106编译通过了，但是NameHash.pro就编译不过了，显示$(error Cannot find version 2021.1 of c186 library...
我去看了我文件里对应的文档是version2024.1

**Comment by Andy-xiaokang** [comment]
我仓库里面有一个文件夹是 CS106b_2021.1
里面对应的版本是 2021的，编译一下这个文件夹里的

**Comment by Henry-qing** [comment]
已解决！感谢大佬！
